Repository openworm/org.geppetto.frontend, pull requests merged in 2018-08, with the labels that each got.

#819 Loading Mechanism feature: fetch variables batch
  src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java
  src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java
  src/main/webapp/js/common/Manager.js
  src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js
  src/main/webapp/js/geppettoModel/model/Datasource.js
Labels: review

#822 No carousel on single image
  src/main/webapp/js/components/interface/query/query.js
Labels: enhancement

#818 use setState instead of mutating state directly in tutorial
  src/main/webapp/js/components/interface/tutorial/Tutorial.js
Labels: ready, review

#824 fix for overlapping content
  src/main/webapp/js/components/interface/query/query.less
Labels: review

#825 adding faint colour to differentiate for click off when few results
  src/main/webapp/js/components/interface/query/query.less
Labels: review

#828 ignoring failed query html response pages
  src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js
Labels: review

#830 Fix for clipping of spotlight buttons
  src/main/webapp/js/components/interface/spotlight/spotlight.less
Labels: review
